#!/bin/bash

while true; do

	dwmupdates > /home/steve/dwmscripts/dwmupdates.txt

	sleep 3600s

done &

while true; do

	HDD=$(dwmdisk)
	TIME=$(dwmclock)
	xsetroot -name "| $HDD |  $TIME"

	sleep 5s
	
done &
